# Generated by Django 4.2.2 on 2023-07-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_remove_comment_modify_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('questions', models.ManyToManyField(related_name='question_category', to='pybo.question')),
            ],
        ),
    ]
