# Generated by Django 4.2.2 on 2023-07-31 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0009_remove_category_questions_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_comment', to='pybo.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_content',
            field=models.TextField(default='', null=True),
        ),
    ]
