# Generated by Django 4.2.2 on 2023-08-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0012_comment_modify_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hits',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=7),
        ),
    ]
